[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksConfig]
# Set the build context to the backend directory
buildCommand = "cd backend && npm install"
